name: yamh
version: 0.1.1
description: Yet Another Markdown to HTML converter. Dirt simple and null-safe. 
repository: https://github.com/doamatto/yamh
issue_tracker: https://github.com/doamatto/yamh/issues
documentation: https://github.com/doamatto/yamh#Usage

dependencies: 
  args: ^2.1.0
  markdown: ^4.0.0
dev_dependencies:
  pedantic: ^1.10.0

environment:
  sdk: '>=2.12.0 <3.0.0'
