name: yamh
description: A dirt simple, null-safe Markdown to HTML converter.
version: 0.1.0
repository: https://github.com/doamatto/yamh

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  args: ^2.1.0
  markdown: ^4.0.0
